name: Mark and Close Stale Issues
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: "This issue is stale due to inactivity. It will be closed in 7 days unless updated."
          close-issue-message: "Closing this issue due to prolonged inactivity."
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: "stale"
          exempt-issue-labels: "pinned,security"
          operations-per-run: 100
